### ISSUE TITLE
Create a reference to the child that's pushed through the StyleManager component

### ISSUE THREAD

**Issue by pvienneau** [mb3online/react-style-manager#21]
From a component rendering out a component wrapped with a StyleManager composite function, I currently reference the StyleManager component, as opposed to the child component. 

I need to be able to reference the child component somehow from outside the StyleManager component.

**Comment by ericadamski** [comment]
@pvienneau could I see an example of the code you are trying to use?

**Comment by pvienneau** [comment]
```
const StatefullyStyledInput = StyleManager(Input);

class App extends React.Component{
    someEventHandler() {
        alert(`Here is the value of the input: ${this.input.ref.child.value}`);
    }

    onChangeHandler() {
        // will this handler be executed?
    }

    render() {
        return (
            <StatefullyStyledInput
                ref={ref => this.input}
                onChange={this.onChangeHandler}
            />
        );
    }
}
```

1) If `someEventHandler` is fired, I need a sure-fire way of accessing the component instance wrapped around the `StyleManager`, without using `this.props.children`
2) Also, can you check to see if props pushed through the composite component are pushed through to its child?
